ALTER TABLE tasks ADD COLUMN IF NOT EXISTS status VARCHAR(20);

UPDATE tasks
SET status = CASE
  WHEN completed = TRUE THEN 'CONCLUIDO'
  ELSE 'A_FAZER'
END
WHERE status IS NULL;

ALTER TABLE tasks ALTER COLUMN status SET NOT NULL;
ALTER TABLE tasks ALTER COLUMN status SET DEFAULT 'A_FAZER';

ALTER TABLE tasks DROP COLUMN IF EXISTS completed;

CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
