import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const fallbackApiBaseUrl = 'http://localhost:8080';
const apiBaseUrl = (process.env.API_BASE_URL || fallbackApiBaseUrl).replace(/\/+$/, '');

const output = `// Auto-generated by scripts/generate-env.mjs\nexport const runtimeConfig = {\n  apiBaseUrl: '${apiBaseUrl}'\n} as const;\n`;

const outputPath = resolve(process.cwd(), 'src/app/config/runtime-config.ts');
writeFileSync(outputPath, output, 'utf8');

console.log(`[env] API_BASE_URL=${apiBaseUrl}`);
