import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const fallbackApiBaseUrl = 'http://localhost:8080';
const configuredApiBaseUrl = process.env.API_BASE_URL || process.env.API_URL || fallbackApiBaseUrl;
const apiBaseUrl = configuredApiBaseUrl.replace(/\/+$/, '');

const output = `// Auto-generated by scripts/generate-env.mjs\nexport const runtimeConfig = {\n  apiBaseUrl: '${apiBaseUrl}'\n} as const;\n`;

const outputPath = resolve(process.cwd(), 'src/app/config/runtime-config.ts');
writeFileSync(outputPath, output, 'utf8');

const source =
  process.env.API_BASE_URL ? 'API_BASE_URL' : process.env.API_URL ? 'API_URL' : 'fallback localhost';
console.log(`[env] ${source}=${apiBaseUrl}`);
